repos:
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        language_version: python3 # Should be a command that runs python3.6+

  - repo: https://github.com/pycqa/flake8
    rev: '3.9.2'
    hooks:
    - id: flake8
      args: [--count, --show-source, --statistics]

  - repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
    - id: nbstripout

